name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update pip
      run: |
        python -m pip install --upgrade pip

    - name: Set up nox
      run: pip install nox

    - name: Run nox tests
      run: nox

    # Добавляем шаги для линтинга
    - name: Set up nox for linting (Python 3.9)
      run: |
        pip install nox
        nox -s lint-3.9

    - name: Set up nox for linting (Python 3.10)
      run: |
        pip install nox
        nox -s lint-3.10

    - name: Set up nox for linting (Python 3.11)
      run: |
        pip install nox
        nox -s lint-3.11
